//! Modern krpano engine static key extraction.
//!
//! Two extraction paths are provided:
//!
//! 1. **Static probe (recommended):** `extract_modern_context` ports the
//!    startup-IIFE checksum, `lf` shuffle, and `charCodes` derivation from
//!    the JS `/tmp/krpano_static_probe.js` into Rust.  It unpacks the
//!    wrapper `krp:` key into `we.subdiv` rows without executing viewer JS,
//!    then reads direct branch-0 row constants.
//!
//! 2. **JSON fallback:** `parse_rows_json` loads pre-extracted rows
//!    (generated by `tools/extract_modern_rows.mjs`) from `rows.json` files
//!    stored alongside each fixture.  This is used in tests as a cross-check.
//!
//! The static probe is the production path — it works with any modern engine
//! without pre-existing data.

use base64::{Engine as _, engine::general_purpose};

use super::EncryptedKrpanoError;

/// Context extracted from a modern krpano engine.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ModernEngineContext {
    /// Default byte-helper key (resolves to "actions overflow" for all current
    /// modern fixtures).
    pub default_key: String,
    /// Replacement token for P/P and R/R branches (resolves to "z").
    pub replacement_token: String,
    /// The constant "KENC" used for header matching.
    pub kenc_constant: String,
    /// Checksum constant that varies by fixture family (22248, 22557, or 23293).
    pub checksum_constant: u32,
    /// Side data from the we.subdiv unpacking, used for widened-key derivation.
    pub side: Vec<u16>,
    /// All unpacked rows, used for row-indexed key lookups.
    pub rows: Vec<Vec<u16>>,
}

/// The `Ma` browser-name array shared by every modern krpano engine.
const MA: [&str; 8] = [
    "krpano",
    "Android Browser",
    "Chrome",
    "Firefox",
    "Gecko",
    "Safari",
    "Internet Explorer",
    "linux",
];

// =========================================================================
// Public API
// =========================================================================

/// Extract modern engine context from a decoded engine JS and wrapper key.
///
/// Returns `Err(Unsupported)` if the engine does not appear to be a modern
/// engine (no startup IIFE found, or unpack failure).
pub fn extract_modern_context(
    decoded_engine: &[u8],
    wrapper_key: &str,
) -> Result<ModernEngineContext, EncryptedKrpanoError> {
    log::debug!(
        "extract_modern_context: engine={} bytes, wrapper_key={} chars",
        decoded_engine.len(),
        wrapper_key.len()
    );
    let text = std::str::from_utf8(decoded_engine)
        .map_err(|_| EncryptedKrpanoError::MissingViewerJsPayload)?;

    let startup = find_startup_iife(text, wrapper_key).ok_or(EncryptedKrpanoError::Unsupported)?;
    log::debug!(
        "extract_modern_context: found startup IIFE, checksum_constant={}",
        startup.constant
    );
    let (rows, side) = unpack_krp_payload(wrapper_key, &startup.body, startup.constant)
        .map_err(|_| EncryptedKrpanoError::Unsupported)?;
    log::debug!(
        "extract_modern_context: unpacked {} rows, {} side values",
        rows.len(),
        side.len()
    );

    let default_key =
        find_row_by_value(&rows, "actions overflow").ok_or(EncryptedKrpanoError::MissingKey)?;
    log::debug!("extract_modern_context: default_key={default_key:?}");

    let replacement_token = find_row_by_value(&rows, "z").unwrap_or_else(|| "z".to_string());
    log::debug!("extract_modern_context: replacement_token={replacement_token:?}");

    Ok(ModernEngineContext {
        default_key,
        replacement_token,
        kenc_constant: "KENC".to_string(),
        checksum_constant: startup.constant,
        side,
        rows,
    })
}

// =========================================================================
// Startup-IIFE location
// =========================================================================

struct StartupIife {
    constant: u32,
    body: String,
}

/// Find the startup key-unpack IIFE structurally:
/// for each `(function …){…}` IIFE, extract numeric literals from the
/// function body as candidate checksum constants, then see whether
/// unpacking the wrapper key succeeds.
fn find_startup_iife(source: &str, wrapper_key: &str) -> Option<StartupIife> {
    let mut search_from = 0;
    while let Some(rel) = source[search_from..].find("(function ") {
        let abs_start = search_from + rel;
        let brace_off = source[abs_start..].find('{')?;
        let abs_brace = abs_start + brace_off;
        let end_brace = matching_brace(source, abs_brace)?;
        let body = source[abs_start + 1..=end_brace].to_string();

        // The checksum constant is a numeric literal in the IIFE body
        // (e.g. `r=22248-v`).  Try every number >= 100 as a candidate.
        for constant in extract_numeric_literals(&body) {
            if constant < 100 {
                continue;
            }
            let k = compute_checksum(function_body(&body));
            let n = constant.wrapping_sub(k);
            if n <= 1 || ((n.wrapping_sub(1)) >> 3) >= 32 {
                continue;
            }
            if unpack_krp_payload(wrapper_key, &body, constant).is_ok() {
                return Some(StartupIife { constant, body });
            }
        }

        search_from = end_brace + 1;
    }
    None
}

/// Extract all unsigned-integer literals from a JS expression string.
fn extract_numeric_literals(src: &str) -> Vec<u32> {
    let mut out = Vec::new();
    let bytes = src.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i].is_ascii_digit() {
            let start = i;
            while i < bytes.len() && bytes[i].is_ascii_digit() {
                i += 1;
            }
            if let Ok(v) = src[start..i].parse::<u32>() {
                out.push(v);
            }
        } else if bytes[i] == b'"' || bytes[i] == b'\'' {
            if let Some((_, next)) = next_js_string_literal(src, i) {
                i = next;
                continue;
            }
            i += 1;
        } else {
            i += 1;
        }
    }
    out
}

/// Find the matching `}` for an opening `{` at `open`.
fn matching_brace(text: &str, open: usize) -> Option<usize> {
    let bytes = text.as_bytes();
    let mut depth: u32 = 0;
    let mut i = open;
    while i < bytes.len() {
        let ch = bytes[i];
        if ch == b'"' || ch == b'\'' {
            let (_, next) = next_js_string_literal(text, i)?;
            i = next;
            continue;
        }
        if ch == b'{' {
            depth += 1;
        }
        if ch == b'}' {
            depth -= 1;
            if depth == 0 {
                return Some(i);
            }
        }
        i += 1;
    }
    None
}

// =========================================================================
// Checksum
// =========================================================================

/// Port of the `qf` checksum function.
fn compute_checksum(source: &str) -> u32 {
    let mut c: u32 = 0;
    for &byte in source.as_bytes() {
        let d = u32::from(byte);
        let g = d.wrapping_sub(36);
        let skip =
            (g == 0) || (12..=21).contains(&g) || (28..=54).contains(&g) || (61..=86).contains(&g);
        if !skip {
            c = c.wrapping_add(d);
        }
    }
    c
}

// =========================================================================
// lf shuffle array
// =========================================================================

/// Build the `lf` shuffle array (port of `Lf`/`buildLf` in JS).
fn build_lf_shuffle() -> Vec<usize> {
    let a = MA[0].len(); // "krpano".len() == 6
    // MA[6] = "Internet Explorer", MA[6][8] = ' ' (space, code 32)
    let ma6_chars: Vec<char> = MA[a].chars().collect();
    let base_c: usize = (ma6_chars[8] as u32 - 1) as usize; // 32 - 1 = 31
    let b = base_c * (a >> 1); // 31 * 3 = 93
    let base: u32 = (base_c + a - 1) as u32; // 31 + 5 = 36
    let c = base_c >> 2; // 31 >> 2 = 7

    let mut f: Vec<usize> = (0..b).collect();
    for g in 0..b {
        let ch = ma6_chars[g & c];
        let digit = ch.to_digit(base).unwrap_or(0) as usize;
        let t = ((g * c) + digit) % b;
        f.swap(g, t);
    }
    let mut m = vec![0usize; b];
    for (g, &val) in f.iter().enumerate() {
        m[val] = g;
    }
    m
}

fn charcodes_offset(s: &str, offset: i32) -> Vec<u32> {
    s.as_bytes()
        .iter()
        .map(|&b| (i32::from(b) + offset) as u32)
        .collect()
}

// =========================================================================
// Unpack wrapper key
// =========================================================================

/// Strip the IIFE function body to just the inner code (port of `rd`).
fn function_body(source: &str) -> &str {
    let start = source.find('{').unwrap() + 1;
    let end = source.rfind('}').unwrap();
    let mut s = start;
    let mut e = end - 1;
    while s < source.len() && source.as_bytes()[s] <= 32 {
        s += 1;
    }
    while e > s && source.as_bytes()[e] <= 32 {
        e -= 1;
    }
    if source.as_bytes()[e] == b';' {
        e -= 1;
    }
    &source[s..=e]
}

/// Unpack a `krp:` wrapper key into `we.subdiv` rows.
///
/// All arithmetic is done in `i32` to match JavaScript 32-bit signed
/// integer semantics (two's complement, wrap on overflow, signed modulo).
fn unpack_krp_payload(
    key: &str,
    startup_body: &str,
    startup_constant: u32,
) -> Result<(Vec<Vec<u16>>, Vec<u16>), String> {
    let lf = build_lf_shuffle();
    let body = function_body(startup_body);
    let k = compute_checksum(body);
    let n = startup_constant.wrapping_sub(k);
    let q = (n.wrapping_sub(1)) >> 3;
    let z_orig = 1 | (n >> q);
    let b_val = z_orig | q;
    let v = (1u32 << b_val).wrapping_sub(1);
    let x = (n.wrapping_sub(1)).wrapping_mul(q).wrapping_sub(1);

    // E = (v << (B+1)) + ((n-q)*z + x) — all 32-bit wrapping
    let e_val = (v as i32).wrapping_shl(b_val + 1).wrapping_add(
        (n.wrapping_sub(q) as i32)
            .wrapping_mul(z_orig as i32)
            .wrapping_add(x as i32),
    );

    // r array: r[d] = d - (d > 1) - (d > 59)
    let r: Vec<i32> = (0..=v as i32)
        .map(|d| d - i32::from(d > 1) - i32::from(d > 59))
        .collect();

    let u_i32: Vec<i32> = charcodes_offset(&format!("<{}>", MA[0]), 0)
        .into_iter()
        .map(|v| v as i32)
        .collect();

    let key_bytes = key.as_bytes();
    let d_len = key_bytes.len().saturating_sub(q as usize);
    let mut t: i32 = i32::from(key_bytes[z_orig as usize - 1]); // JS: key.charCodeAt(z-1)
    let mut d = z_orig as usize;
    let mut rows: Vec<Vec<u16>> = Vec::new();
    let mut side: Vec<u16> = Vec::new();
    let mut current: Vec<u16> = Vec::new();
    let mut e_flag: i32 = 1;
    let mut h: i32 = 0;

    while d < d_len {
        let key_char = i32::from(key_bytes[d]);
        // JS: r[(key.charCodeAt(d) - n) & v]
        let r_idx = ((key_char - n as i32) & (v as i32)) as usize;
        let rv = r[r_idx];
        let ud = u_i32[d & (b_val as usize)];
        // JS: (rv + d*q + ud + t) % (x + 1)
        let lf_idx = (rv + (d as i32) * (q as i32) + ud + t).rem_euclid(x as i32 + 1) as usize;
        let g: i32 = lf[lf_idx] as i32;

        // JS: t = ((t << (q+1)) + t*B + g) % E
        t = t
            .wrapping_shl((q + 1) as u32)
            .wrapping_add(t.wrapping_mul(b_val as i32))
            .wrapping_add(g)
            .rem_euclid(e_val);

        if g == x as i32 {
            // separator
            if e_flag == 0 {
                h = (h + 1) & 1;
            } else if h != 0 {
                h = 0;
            } else {
                rows.push(std::mem::take(&mut current));
                current = Vec::new();
                e_flag = 0;
            }
        } else {
            let gv = (g + n as i32) as u16;
            if h == 0 {
                current.push(gv);
            } else {
                side.push(gv);
            }
            e_flag += 1;
        }
        d += 1;
    }
    if e_flag > 0 {
        rows.push(current);
    }

    // Final checksum verification (q more bytes) — uses ORIGINAL z, not widened
    // JS: for (D += q; d < D;) g = (g << z) | (key.charCodeAt(d++) - (10 * z + q));
    // After this loop: const ok = g === t;
    // Only THEN does JS widen z: z = z | (z << (z-1)) | (z << 1);
    let mut gv: i32 = 0;
    let d2_len = d_len + q as usize;
    while d < d2_len {
        // JS << masks shift to lower 5 bits
        let shifted = gv.wrapping_shl((z_orig & 31) as u32);
        let rhs = i32::from(key_bytes[d]) - (10 * z_orig + q) as i32;
        gv = shifted | rhs;
        d += 1;
    }
    if gv != t {
        return Err(format!("checksum mismatch: got {gv}, expected {t}"));
    }
    Ok((rows, side))
}

// =========================================================================
// Direct row reads
// =========================================================================

/// Search all unpacked rows for a row whose string value equals `target`.
fn find_row_by_value(rows: &[Vec<u16>], target: &str) -> Option<String> {
    for row in rows {
        if row.is_empty() {
            continue;
        }
        let s: String = row
            .iter()
            .map(|&c| char::from_u32(u32::from(c)).unwrap_or('?'))
            .collect();
        if s == target {
            return Some(s);
        }
    }
    None
}

// =========================================================================
// P/P and R/R subdiv branch
// =========================================================================

/// Decode the modern `P/P` and 2023-style `R/R` XML body.
///
/// krpano first replaces the configured token (`z` in current fixtures) with
/// `\`, then sends the result to `we.subdiv` branch 5 via the XML parser
/// (`_(9493, body, 1)`).  `R/R` bodies additionally read the `pk=` protection
/// record from the wrapper-key side data through the branch-12 trie.
pub fn pp_rr_branch_to_plaintext(
    body: &str,
    ctx: &ModernEngineContext,
) -> Result<String, EncryptedKrpanoError> {
    if ctx.replacement_token.is_empty() {
        return Err(EncryptedKrpanoError::Unsupported);
    }
    let replaced = body.replace(&ctx.replacement_token, "\\");
    let row = find_krpano_row(&ctx.rows).ok_or(EncryptedKrpanoError::Unsupported)?;
    let protection_key = extract_protection_key(ctx)?;
    let plaintext = subdiv_branch5_decode(&replaced, row, protection_key.as_deref())?;
    let normalized = plaintext.trim_start_matches('\u{feff}').trim_start();
    if normalized.starts_with("<krpano") {
        Ok(plaintext)
    } else {
        Err(EncryptedKrpanoError::Unsupported)
    }
}

fn find_krpano_row(rows: &[Vec<u16>]) -> Option<&[u16]> {
    rows.iter().find_map(|row| {
        if row.iter().copied().eq("krpano".bytes().map(u16::from)) {
            Some(row.as_slice())
        } else {
            None
        }
    })
}

fn extract_protection_key(
    ctx: &ModernEngineContext,
) -> Result<Option<String>, EncryptedKrpanoError> {
    let records = side_records(ctx)?;
    let key = records
        .into_iter()
        .find_map(|record| record.strip_prefix("pk=").map(ToOwned::to_owned));
    if let Some(key) = &key {
        log::debug!(
            "extract_protection_key: found pk= record ({} chars)",
            key.len()
        );
    } else {
        log::debug!("extract_protection_key: no pk= record in side data");
    }
    Ok(key)
}

fn side_records(ctx: &ModernEngineContext) -> Result<Vec<String>, EncryptedKrpanoError> {
    if ctx.side.is_empty() {
        return Ok(Vec::new());
    }
    let encoded: String = ctx
        .side
        .iter()
        .filter_map(|&c| char::from_u32(u32::from(c)))
        .collect();
    let decoded = general_purpose::STANDARD
        .decode(encoded.as_bytes())
        .map_err(|_| EncryptedKrpanoError::Unsupported)?;
    let text = krpano_utf8_decode(&decoded);
    Ok(text.split(';').map(str::to_owned).collect())
}

fn subdiv_branch5_decode(
    input: &str,
    row: &[u16],
    protection_key: Option<&str>,
) -> Result<String, EncryptedKrpanoError> {
    let d = input.as_bytes();
    if d.len() < 2 || row.len() <= 5 {
        return Err(EncryptedKrpanoError::Unsupported);
    }

    let g = i64::from(row[5]) / 3;
    if g <= 0 {
        return Err(EncryptedKrpanoError::Unsupported);
    }
    let f = i64::from(d[0]) - g;
    let mut h = i64::from(d[1]) - g;
    if f != 0 && f != 1 {
        return Err(EncryptedKrpanoError::Unsupported);
    }
    if f == 1 && protection_key.is_none() {
        return Err(EncryptedKrpanoError::MissingKey);
    }
    if h <= 0 {
        return Err(EncryptedKrpanoError::Unsupported);
    }

    let mut k = 2_i64;
    let mut m = 3_i64;
    let mut v = h + k;
    let q = (v * h + h) / h;
    let t = v + h * k;
    let w = t * t * h;
    let p = w * t * h;
    let big_b = p * h * h;
    let big_f = big_b * v * h;
    let big_n = (p + w) * (g - k) + k * v * (g + v - 1);
    let a = p * m / w;
    let g_len = usize::try_from(g).map_err(|_| EncryptedKrpanoError::Unsupported)?;
    let mut stream = usize::try_from(k).map_err(|_| EncryptedKrpanoError::Unsupported)?;
    let mut keys = vec![0_i64; g_len];

    for key in &mut keys {
        if stream + 1 >= d.len() {
            return Err(EncryptedKrpanoError::Unsupported);
        }
        *key = big_b * i64::from(d[stream]) * v + (i64::from(d[stream + 1]) - g + h) * w;
        stream += 2;
    }

    if f == 1 {
        let key = protection_key.ok_or(EncryptedKrpanoError::MissingKey)?;
        let trie_x = 1_i64;
        let trie_y: Vec<i64> = key.bytes().map(|byte| i64::from(byte) + trie_x).collect();
        k = -trie_x;
        let mask = a * (1 + (a + 1) * (1 + (a + 1) * (1 + (a + 1))));
        let idx1_base = usize::try_from(v).map_err(|_| EncryptedKrpanoError::MissingKey)?;
        let idx2_base = usize::try_from(t * m).map_err(|_| EncryptedKrpanoError::MissingKey)?;
        let idx3_base = usize::try_from(t * v).map_err(|_| EncryptedKrpanoError::MissingKey)?;
        for (r, key) in keys.iter_mut().enumerate() {
            let idx1 = idx1_base + r;
            let idx2 = idx2_base + r;
            let idx3 = idx3_base
                .checked_sub(r)
                .ok_or(EncryptedKrpanoError::MissingKey)?;
            if idx1 >= trie_y.len() || idx2 >= trie_y.len() || idx3 >= trie_y.len() {
                return Err(EncryptedKrpanoError::MissingKey);
            }
            let mixed =
                *key + big_n * (trie_y[idx1] + k) + t * (trie_y[idx2] + k) - a * (trie_y[idx3] + k);
            *key = js_bitand(mixed, mask);
        }
    }

    let ba = i64::try_from(d.len()).map_err(|_| EncryptedKrpanoError::Unsupported)?;
    let r_len = ((ba - 2 * (1 + g)) * q / h) >> 1;
    if r_len < 0 {
        return Err(EncryptedKrpanoError::Unsupported);
    }
    let mut rbuf =
        vec![0_u8; usize::try_from(r_len).map_err(|_| EncryptedKrpanoError::Unsupported)?];
    let mut src = usize::try_from(2 * (1 + g)).map_err(|_| EncryptedKrpanoError::Unsupported)?;
    let mut out_a = 0_usize;
    let mut e = 0_usize;
    let mut out_b = 2_usize;

    while src < d.len() {
        if src + 4 >= d.len() {
            return Err(EncryptedKrpanoError::Unsupported);
        }
        let mut b = t * (i64::from(d[src]) * big_b - big_f)
            + i64::from(d[src + 1])
            + h * (i64::from(d[src + 2]) * w
                + i64::from(d[src + 3]) * p
                + i64::from(d[src + 4]) * t
                - big_n);
        let key = keys[e];
        b = b + key - 2 * js_bitand(b, key);
        v = js_shr(b, q);
        e += 1;
        if e >= g_len {
            e = 0;
        }
        let n = js_shr(v, q);
        src += 5;
        let f3 = js_shr(n, q);
        if out_a + 1 >= rbuf.len() || out_b + 1 >= rbuf.len() {
            return Err(EncryptedKrpanoError::Unsupported);
        }
        rbuf[out_a] = f3 as u8;
        rbuf[out_a + 1] = js_bitand(n, a) as u8;
        rbuf[out_b] = js_bitand(v, a) as u8;
        rbuf[out_b + 1] = js_bitand(b, a) as u8;
        out_a += 4;
        out_b += 4;
    }

    let n_base = a + 1;
    let half_q = q / 2;
    let half = usize::try_from(half_q).map_err(|_| EncryptedKrpanoError::Unsupported)?;
    if rbuf.len() <= half + 3 || rbuf.len() < 4 {
        return Err(EncryptedKrpanoError::Unsupported);
    }
    let out_len = i64::from(rbuf[0])
        + i64::from(rbuf[1]) * n_base
        + i64::from(rbuf[2]) * n_base * n_base
        + i64::from(rbuf[3]) * n_base * n_base * n_base;
    if out_len < 0 {
        return Err(EncryptedKrpanoError::Unsupported);
    }
    let mut out =
        vec![0_u8; usize::try_from(out_len).map_err(|_| EncryptedKrpanoError::Unsupported)?];
    let ba = i64::from(rbuf[half])
        + q
        + (i64::from(rbuf[half + 1])
            + n_base * (i64::from(rbuf[half + 2]) + n_base * i64::from(rbuf[half + 3])))
            * n_base;
    if ba < 0 {
        return Err(EncryptedKrpanoError::Unsupported);
    }
    let ba = usize::try_from(ba).map_err(|_| EncryptedKrpanoError::Unsupported)?;
    let n = a - t + 2;
    let mut read = usize::try_from(q).map_err(|_| EncryptedKrpanoError::Unsupported)?;
    let mut write = 0_usize;
    while read < ba {
        if read >= rbuf.len() {
            return Err(EncryptedKrpanoError::Unsupported);
        }
        v = i64::from(rbuf[read]);
        read += 1;
        k = js_shr(v, half_q);
        m = k + n;
        while m == a {
            if read >= rbuf.len() {
                return Err(EncryptedKrpanoError::Unsupported);
            }
            m = i64::from(rbuf[read]);
            read += 1;
            k += m;
        }
        let literal_len = usize::try_from(k).map_err(|_| EncryptedKrpanoError::Unsupported)?;
        if read + literal_len > rbuf.len() || write + literal_len > out.len() {
            return Err(EncryptedKrpanoError::Unsupported);
        }
        out[write..write + literal_len].copy_from_slice(&rbuf[read..read + literal_len]);
        read += literal_len;
        write += literal_len;

        if read < ba {
            if read + 1 >= rbuf.len() {
                return Err(EncryptedKrpanoError::Unsupported);
            }
            let offset = i64::from(rbuf[read]) | (i64::from(rbuf[read + 1]) << q);
            read += 2;
            h = i64::try_from(write).map_err(|_| EncryptedKrpanoError::Unsupported)? - offset;
            if h < 0 {
                return Err(EncryptedKrpanoError::Unsupported);
            }
            k = js_bitand(v, t - 2);
            m = k + n;
            while m == a {
                if read >= rbuf.len() {
                    return Err(EncryptedKrpanoError::Unsupported);
                }
                m = i64::from(rbuf[read]);
                read += 1;
                k += m;
            }
            let copy_len =
                usize::try_from(k + half_q).map_err(|_| EncryptedKrpanoError::Unsupported)?;
            let mut copy_from =
                usize::try_from(h).map_err(|_| EncryptedKrpanoError::Unsupported)?;
            if write + copy_len > out.len() {
                return Err(EncryptedKrpanoError::Unsupported);
            }
            for _ in 0..copy_len {
                if copy_from >= write {
                    return Err(EncryptedKrpanoError::Unsupported);
                }
                out[write] = out[copy_from];
                write += 1;
                copy_from += 1;
            }
        }
    }

    Ok(krpano_utf8_decode(&out))
}

fn js_shr(value: i64, shift: i64) -> i64 {
    i64::from((value as i32) >> ((shift as u32) & 31))
}

fn js_bitand(lhs: i64, rhs: i64) -> i64 {
    i64::from((lhs as i32) & (rhs as i32))
}

fn krpano_utf8_decode(input: &[u8]) -> String {
    let mut out = String::new();
    let mut idx = 0;
    while idx < input.len() {
        let d = input[idx];
        if d < 128 {
            if d > 0 {
                out.push(char::from(d));
            }
            idx += 1;
        } else if d > 191 && d < 224 {
            if idx + 1 >= input.len() {
                break;
            }
            let e = input[idx + 1];
            let code = (u32::from(d & 31) << 6) | u32::from(e & 63);
            if let Some(ch) = char::from_u32(code) {
                out.push(ch);
            }
            idx += 2;
        } else {
            if idx + 2 >= input.len() {
                break;
            }
            let e = input[idx + 1];
            let g = input[idx + 2];
            let code = (u32::from(d & 15) << 12) | (u32::from(e & 63) << 6) | u32::from(g & 63);
            if code != 0xfeff {
                if let Some(ch) = char::from_u32(code) {
                    out.push(ch);
                }
            }
            idx += 3;
        }
    }
    out
}

// =========================================================================
// JSON fallback
// =========================================================================

/// The JSON format produced by `tools/extract_modern_rows.mjs`.
#[cfg(test)]
use serde::Deserialize;

#[cfg(test)]
use std::collections::HashMap;

#[cfg(test)]
#[derive(Deserialize)]
struct RowsJson {
    checksum_constant: u32,
    #[serde(default)]
    rows: HashMap<String, String>,
}

/// Search all JSON rows for a row whose decoded value equals `target`.
#[cfg(test)]
fn find_row_json_by_value(rows: &HashMap<String, String>, target: &str) -> Option<String> {
    for hex in rows.values() {
        let bytes: Vec<u8> = (0..hex.len())
            .step_by(2)
            .filter_map(|i| u8::from_str_radix(&hex[i..i + 2], 16).ok())
            .collect();
        if bytes.is_empty() {
            continue;
        }
        if let Ok(s) = String::from_utf8(bytes) {
            if s == target {
                return Some(s);
            }
        }
    }
    None
}

/// Parse a rows.json file and extract the `ModernEngineContext`.
/// Used as a cross-check in tests.
#[cfg(test)]
pub fn parse_rows_json(json: &str) -> Option<ModernEngineContext> {
    let data: RowsJson = serde_json::from_str(json).ok()?;
    let default_key = find_row_json_by_value(&data.rows, "actions overflow")?;
    let replacement_token =
        find_row_json_by_value(&data.rows, "z").unwrap_or_else(|| "z".to_string());
    Some(ModernEngineContext {
        default_key,
        replacement_token,
        kenc_constant: "KENC".to_string(),
        checksum_constant: data.checksum_constant,
        side: Vec::new(),
        rows: Vec::new(),
    })
}

// =========================================================================
// JS string-literal lexer (for matching_brace)
// =========================================================================

fn next_js_string_literal(text: &str, start: usize) -> Option<(String, usize)> {
    let bytes = text.as_bytes();
    let mut idx = start;
    let quote = bytes.get(idx)?;
    if *quote != b'"' && *quote != b'\'' {
        return None;
    }
    idx += 1;
    let mut literal = String::new();
    while idx < bytes.len() {
        let byte = bytes[idx];
        if byte == *quote {
            return Some((literal, idx + 1));
        }
        if byte == b'\\' {
            idx += 1;
            if idx >= bytes.len() {
                return None;
            }
            match bytes[idx] {
                b'x' => {
                    let v = hex_digit(bytes.get(idx + 1)?)? as u32 * 16
                        + hex_digit(bytes.get(idx + 2)?)? as u32;
                    literal.push(char::from_u32(v)?);
                    idx += 3;
                }
                b'u' => {
                    let v = hex_digit(bytes.get(idx + 1)?)? as u32 * 4096
                        + hex_digit(bytes.get(idx + 2)?)? as u32 * 256
                        + hex_digit(bytes.get(idx + 3)?)? as u32 * 16
                        + hex_digit(bytes.get(idx + 4)?)? as u32;
                    literal.push(char::from_u32(v)?);
                    idx += 5;
                }
                b'\r' => {
                    idx += 1;
                    if idx < bytes.len() && bytes[idx] == b'\n' {
                        idx += 1;
                    }
                }
                b'\n' => {
                    idx += 1;
                }
                b'b' => {
                    literal.push('\u{0008}');
                    idx += 1;
                }
                b'f' => {
                    literal.push('\u{000c}');
                    idx += 1;
                }
                b'n' => {
                    literal.push('\n');
                    idx += 1;
                }
                b'r' => {
                    literal.push('\r');
                    idx += 1;
                }
                b't' => {
                    literal.push('\t');
                    idx += 1;
                }
                b'v' => {
                    literal.push('\u{000b}');
                    idx += 1;
                }
                escaped => {
                    literal.push(char::from(escaped));
                    idx += 1;
                }
            }
            continue;
        }
        literal.push(char::from(byte));
        idx += 1;
    }
    None
}

fn hex_digit(byte: &u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

// =========================================================================
// Tests
// =========================================================================

#[cfg(test)]
mod tests {
    use super::super::viewer;
    use super::*;
    use std::fs;
    use std::path::Path;

    fn load_fixture(fixture: &str) -> Option<(Vec<u8>, String)> {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/krpano/encrypted")
            .join(fixture);
        let js = ["tour.js", "krpano.js"]
            .iter()
            .map(|n| root.join(n))
            .find(|p| p.exists())?;
        let js_data = fs::read(&js).ok()?;
        let decoded = viewer::extract_decoded_viewer_js(&js_data).ok()?;
        let key = viewer::extract_key_from_viewer_js(&js_data)?;
        Some((decoded, key))
    }

    // ---- static probe path ----

    #[test]
    fn static_probe_extracts_default_key() {
        for name in [
            "2018-04-04",
            "2023-02-07",
            "2023-04-30",
            "2023-12-11",
            "2024-12-20",
            "2026-06-25-pp-01_minimal",
            "2026-06-25-rr_minimal",
        ] {
            let (decoded, key) = load_fixture(name).expect(name);
            let ctx =
                extract_modern_context(&decoded, &key).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(ctx.default_key, "actions overflow", "{name}");
        }
    }

    #[test]
    fn static_probe_extracts_replacement_token() {
        for name in [
            "2018-04-04",
            "2023-02-07",
            "2023-04-30",
            "2023-04-30-PP",
            "2023-12-11",
            "2024-12-20",
            "2026-06-25-pp-01_minimal",
            "2026-06-25-rr_minimal",
        ] {
            let (decoded, key) = load_fixture(name).expect(name);
            let ctx =
                extract_modern_context(&decoded, &key).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(ctx.replacement_token, "z", "{name}");
        }
    }

    #[test]
    fn static_probe_extracts_correct_checksum_constant() {
        let expected = [
            ("2018-04-04", 22248),
            ("2023-02-07", 22557),
            ("2023-04-30", 23293),
            ("2023-12-11", 23293),
            ("2024-12-20", 23293),
            ("2026-06-25-pp-01_minimal", 23293),
            ("2026-06-25-rr_minimal", 23293),
        ];
        for (name, exp) in expected {
            let (decoded, key) = load_fixture(name).expect(name);
            let ctx =
                extract_modern_context(&decoded, &key).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(ctx.checksum_constant, exp, "{name}");
        }
    }

    #[test]
    fn static_probe_rejects_old_engine() {
        let (decoded, key) = load_fixture("old").expect("old");
        assert!(extract_modern_context(&decoded, &key).is_err());
    }

    #[test]
    fn side_data_exposes_2023_protection_key() {
        let (decoded, key) = load_fixture("2023-04-30").expect("2023-04-30");
        let ctx = extract_modern_context(&decoded, &key).unwrap();
        let key = extract_protection_key(&ctx).unwrap().expect("pk= record");
        assert_eq!(key.len(), 128);
        assert!(key.starts_with("UZbbbXZHUbbb"));
    }

    #[test]
    fn subdiv_branch5_decrypts_2023_rr_fixture() {
        let root =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("testdata/krpano/encrypted/2023-04-30");
        let xml = fs::read(root.join("tour.xml")).unwrap();
        let payload = viewer::encrypted_payload(&xml).unwrap();
        let header = super::super::header::KencHeader::parse(&payload).unwrap();
        let body = header.payload(&payload);
        let (decoded, key) = load_fixture("2023-04-30").expect("2023-04-30");
        let ctx = extract_modern_context(&decoded, &key).unwrap();

        let plaintext = pp_rr_branch_to_plaintext(body, &ctx).unwrap();
        assert_eq!(plaintext.len(), 14_937);
        assert!(plaintext.trim_start().starts_with("<krpano"));
    }

    #[test]
    fn subdiv_branch5_decrypts_2023_pp_fixture() {
        let root =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("testdata/krpano/encrypted/2023-04-30-PP");
        let xml = fs::read(root.join("tour.xml")).unwrap();
        let payload = viewer::encrypted_payload(&xml).unwrap();
        let header = super::super::header::KencHeader::parse(&payload).unwrap();
        let body = header.payload(&payload);
        let (decoded, key) = load_fixture("2023-04-30-PP").expect("2023-04-30-PP");
        let ctx = extract_modern_context(&decoded, &key).unwrap();

        let plaintext = pp_rr_branch_to_plaintext(body, &ctx).unwrap();
        assert_eq!(plaintext.len(), 1_859);
        assert!(plaintext.trim_start().starts_with("<krpano"));
    }

    #[test]
    #[ignore]
    fn analysis_prints_krpano_124_context_clues() {
        for name in ["2026-06-25-pp-01_minimal", "2026-06-25-rr_minimal"] {
            let (decoded, key) = load_fixture(name).expect(name);
            let text = std::str::from_utf8(&decoded).expect(name);
            eprintln!("{name}: decoded={} wrapper={}", decoded.len(), key.len());
            for needle in [
                "KENC",
                "actions overflow",
                "decodeLicense",
                "decryptData",
                "subdiv",
                "loadpano",
                "embedhtml5",
                "String.fromCharCode",
                "replaceAll",
                ".replace",
            ] {
                match text.find(needle) {
                    Some(idx) => {
                        let start = idx.saturating_sub(120);
                        let end = (idx + needle.len() + 240).min(text.len());
                        eprintln!("{name}: {needle:?} at {idx}: {}", &text[start..end]);
                    }
                    None => eprintln!("{name}: {needle:?} not found"),
                }
            }
            match extract_modern_context(&decoded, &key) {
                Ok(ctx) => eprintln!("{name}: context={ctx:?}"),
                Err(err) => eprintln!("{name}: context error={err}"),
            }
            if let Some(startup) = find_startup_iife(text, &key) {
                let (rows, _side) =
                    unpack_krp_payload(&key, &startup.body, startup.constant).unwrap();
                eprintln!("{name}: rows={}", rows.len());
                for (idx, row) in rows.iter().enumerate() {
                    let value: String = row
                        .iter()
                        .map(|&c| char::from_u32(u32::from(c)).unwrap_or('?'))
                        .collect();
                    if value == "KENC"
                        || value == "z"
                        || value == "\\"
                        || value.contains("actions")
                        || value.contains("encrypt")
                        || value.contains("xml")
                    {
                        eprintln!("{name}: row[{idx}]={value:?}");
                    }
                }
                for row in [82usize, 87, 89, 114, 119] {
                    for id in possible_direct_row_ids(row) {
                        let needle = format!("_({id}");
                        if let Some(idx) = text.find(&needle) {
                            let start = idx.saturating_sub(300);
                            let end = (idx + 2600).min(text.len());
                            eprintln!(
                                "{name}: row {row} call {needle:?} at {idx}: {}",
                                &text[start..end]
                            );
                        }
                    }
                }
                for needle in [
                    "37==",
                    "42==",
                    "charCodeAt(0)",
                    "charCodeAt(1)",
                    "slice(2",
                    "indexOf(\"@\"",
                    "indexOf('@'",
                ] {
                    print_first_matches(name, text, needle, 4);
                }
            }
        }
    }

    fn possible_direct_row_ids(row: usize) -> Vec<usize> {
        let mut ids = Vec::new();
        for branch in 0..16usize {
            ids.push((branch << 11) | (row << 2));
            ids.push(1 | (row << 7) | (branch << 2));
        }
        ids
    }

    fn print_first_matches(name: &str, text: &str, needle: &str, limit: usize) {
        let mut search_from = 0;
        let mut found = 0;
        while found < limit {
            let Some(rel) = text[search_from..].find(needle) else {
                break;
            };
            let idx = search_from + rel;
            let start = idx.saturating_sub(180);
            let end = (idx + needle.len() + 360).min(text.len());
            eprintln!("{name}: {needle:?} at {idx}: {}", &text[start..end]);
            search_from = idx + needle.len();
            found += 1;
        }
    }

    // ---- JSON cross-check path ----

    fn load_rows_json(fixture: &str) -> String {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/krpano/encrypted")
            .join(fixture)
            .join("rows.json");
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("{fixture}: {e}"))
    }

    #[test]
    #[ignore]
    fn try_all_rows_as_rr_keys_for_2023_04_30() {
        // Try every row value from the 2023-04-30 rows.json as a potential RR key
        let json = load_rows_json("2023-04-30");
        let root =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("testdata/krpano/encrypted/2023-04-30");
        let xml = fs::read(root.join("tour.xml")).unwrap();
        let payload = viewer::encrypted_payload(&xml).unwrap();
        let header = super::super::header::KencHeader::parse(&payload).unwrap();
        let body = header.payload(&payload);

        let rows_json: RowsJson = serde_json::from_str(&json).unwrap();
        for (row_id, hex) in &rows_json.rows {
            let bytes: Vec<u8> = (0..hex.len())
                .step_by(2)
                .filter_map(|i| u8::from_str_radix(&hex[i..i + 2], 16).ok())
                .collect();
            if bytes.is_empty() || bytes.len() > 64 {
                continue;
            }
            if let Ok(s) = String::from_utf8(bytes.clone()) {
                if s == "actions overflow" || s == "z" || s == "KENC" {
                    continue; // skip known non-key values
                }
            }
            match crate::krpano::encrypted::branches::decrypt_rr_branch(body, &bytes) {
                Ok(plaintext) => {
                    eprintln!(
                        "KEY FOUND: row {row_id} key={:?} plaintext={:.80}",
                        bytes, plaintext
                    );
                }
                Err(_) => {}
            }
        }
        eprintln!("done");
    }
    #[test]
    fn json_and_static_probe_agree_on_rows() {
        for name in [
            "2018-04-04",
            "2023-02-07",
            "2023-04-30",
            "2023-04-30-PP",
            "2023-12-11",
            "2024-12-20",
        ] {
            let (decoded, key) = load_fixture(name).expect(name);
            let ctx_static = extract_modern_context(&decoded, &key)
                .unwrap_or_else(|e| panic!("{name} static: {e}"));
            let json = load_rows_json(name);
            let ctx_json =
                parse_rows_json(&json).unwrap_or_else(|| panic!("{name} json parse failed"));
            assert_eq!(
                ctx_static.default_key, ctx_json.default_key,
                "{name}: default_key"
            );
            assert_eq!(
                ctx_static.replacement_token, ctx_json.replacement_token,
                "{name}: replacement_token"
            );
            assert_eq!(
                ctx_static.checksum_constant, ctx_json.checksum_constant,
                "{name}: checksum"
            );
        }
    }
}
